def get_error_details():
    return(2, 'second err')
